# Generated by Django 5.2.11 on 2026-02-23 15:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=64, unique=True)),
                ('content', models.CharField(default='content', max_length=1024)),
                ('isVisible', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date(2026, 2, 23))),
                ('modified_date', models.DateField(default=datetime.date(2026, 2, 23))),
                ('visibleUntil', models.DateField(default=datetime.date(2026, 2, 23))),
                ('image', models.CharField(default='', max_length=1000000)),
                ('location', models.CharField(default='location', max_length=128)),
            ],
            options={
                'db_table': 'accomplishments',
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=64, unique=True)),
                ('content', models.CharField(default='content', max_length=1024)),
                ('isVisible', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date(2026, 2, 23))),
                ('modified_date', models.DateField(default=datetime.date(2026, 2, 23))),
                ('visibleUntil', models.DateField(default=datetime.date(2026, 2, 23))),
                ('image', models.CharField(default='', max_length=1000000)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
    ]
