# Generated by Django 4.1.13 on 2026-02-24 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishement',
            name='creation_date',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
        migrations.AlterField(
            model_name='accomplishement',
            name='modified_date',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
        migrations.AlterField(
            model_name='accomplishement',
            name='visibleUntil',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_date',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibleUntil',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
    ]
