# Generated by Django 4.1.13 on 2024-06-12 00:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=64, unique=True)),
                ('content', models.CharField(default='content', max_length=7500)),
                ('creation_date', models.DateTimeField(default=datetime.date(2024, 6, 11))),
                ('image', models.CharField(default='', max_length=1000000)),
            ],
            options={
                'db_table': 'modal_content',
            },
        ),
    ]
