# Generated by Django 4.1.13 on 2024-06-12 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_text_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 6, 11)),
        ),
    ]
