# Generated by Django 5.2.11 on 2026-02-23 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_text_content', '0002_alter_modaltext_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='creation_date',
            field=models.DateField(default=datetime.date(2026, 2, 23)),
        ),
    ]
