# Generated by Django 4.1.13 on 2026-02-24 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_text_content', '0003_alter_modaltext_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='creation_date',
            field=models.DateField(default=datetime.date(2026, 2, 24)),
        ),
    ]
